import logging
import datetime
import os

class BaseConfig(object):
    DEBUG =
    TESTING =
    LOGGING_FORMAT =
    LOGGING_LEVEL =
    LOGGING_LOCATION =

    POSTGRES_HOST =
    POSTGRES_PORT =
    POSTGRES_USER =
    POSTGRES_PASSWORD =
    POSTGRES_DB =

    NEW_POSTGRES_HOST =
    NEW_POSTGRES_PORT =
    NEW_POSTGRES_USER =
    NEW_POSTGRES_PASSWORD =
    NEW_POSTGRES_DB =

    CREDENTIAL_PATH =
    GCS_BUCKET_NAME =
    PROVIDER_ACCOUNT_PUB_KEYS_FILE =
    SURVEY_INTERVAL_MINUTES =
    UPTIME_DAYS_FOR_SCORE =
    FROM_EMAIL =
    TO_EMAILS =
    SUBJECT =
    PLAIN_TEXT =
    SENDGRID_API_KEY =
    SPREADSHEET_SCOPE =
    SPREADSHEET_NAME =
    SPREADSHEET_JSON =
    MAX_THREADS_TO_DOWNLOAD_FILES=