import logging
import datetime

class BaseConfig(object):
    LOGGING_FORMAT = 
    LOGGING_LOCATION = 
    POSTGRES_ARCHIVE_HOST = 
    POSTGRES_ARCHIVE_PORT = 
    POSTGRES_ARCHIVE_USER = 
    POSTGRES_ARCHIVE_PASSWORD = 
    POSTGRES_ARCHIVE_DB = 
    # POSTGRES_ARCHIVE_DB = 

    POSTGRES_PAYOUT_HOST = 
    POSTGRES_PAYOUT_PORT = 
    POSTGRES_PAYOUT_USER = 
    POSTGRES_PAYOUT_PASSWORD = 
    POSTGRES_PAYOUT_DB = 
    # POSTGRES_PAYOUT_DB = 

    POSTGRES_LEADERBOARD_HOST = 
    POSTGRES_LEADERBOARD_PORT = 
    POSTGRES_LEADERBOARD_USER = 
    POSTGRES_LEADERBOARD_PASSWORD = 
    POSTGRES_LEADERBOARD_DB = 

    FROM_EMAIL = 
    PROVIDER_EMAIL = 
    OVERRIDE_EMAIL = 
    SEND_EMAIL_TO_BP = 

    COINBASE = 
    SLOT_WINDOW_VALUE = 
    CREDENTIAL_PATH = 
    GCS_BUCKET_NAME = 
    SENDGRID_API_KEY = 
    SPREADSHEET_SCOPE = 
    SPREADSHEET_NAME = 
    CALCULATE_EMAIL_TEMPLATE = 
    VALIDATE_EMAIL_TEMPLATE = 
    BURN_EMAIL_TEMPLATE = 
    ADDRESS_SUBJECT = 

    DELEGATION_ADDRESSS_CSV = 
    GENESIS_DATE = 
    CALCULATION_CSV_FILE = 
    VALIDATION_CSV_FILE = 
    ONE_WALLET_SHEET_PATH = 
    ONE_WALLET_SHEET_NAME = 
    SPREADSHEET_JSON = 